### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Services.AsynchronousOperationException
  id: AsynchronousOperationException
  children:
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: AsynchronousOperationException
  nameWithType: AsynchronousOperationException
  fullName: System.IdentityModel.Services.AsynchronousOperationException
  type: Class
  summary: "De uitzondering die wordt gegenereerd wanneer een fout tijdens een asynchrone bewerking optreedt."
  syntax:
    content: 'public class AsynchronousOperationException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException()
  nameWithType: AsynchronousOperationException.AsynchronousOperationException()
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException()
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klasse."
  remarks: "Deze constructor initialiseert de <xref:SystemException.Message>eigenschap van het nieuwe exemplaar voor een systeem geleverd bericht met een beschrijving van de fout.</xref:SystemException.Message> Dit bericht wordt rekening gehouden met de huidige systeemcultuur.       De volgende tabel toont de eerste waarden voor het nieuwe exemplaar.      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException>| `null`.|   | <xref:System.Exception.Message>| De gelokaliseerde fouttekenreeks bericht. |</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: public AsynchronousOperationException ();
    parameters: []
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)
  id: '#ctor(System.Exception)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(Exception)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klasse met een foutbericht met systeem geleverd en een verwijzing naar de interne uitzondering dat de oorzaak van deze uitzondering."
  remarks: "Een uitzondering die is gegenereerd als direct resultaat van een eerdere uitzondering moet een verwijzing bevatten naar de vorige uitzondering in de <xref:System.Exception.InnerException>eigenschap.</xref:System.Exception.InnerException> De <xref:System.Exception.InnerException>eigenschap dezelfde waarde die is doorgegeven aan de constructor.</xref:System.Exception.InnerException>       De volgende tabel toont de eerste waarden voor het nieuwe exemplaar.      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException>| De verwijzing naar de interne uitzondering. |   | <xref:System.Exception.Message>| Een systeem geleverd bericht met een beschrijving van de fout.</xref:System.Exception.Message> </xref:System.Exception.InnerException> Dit bericht rekening gehouden met de huidige systeemcultuur. |"
  syntax:
    content: public AsynchronousOperationException (Exception innerException);
    parameters:
    - id: innerException
      type: System.Exception
      description: "De <xref:System.Exception>die de oorzaak van de huidige uitzondering.</xref:System.Exception> Als de `innerException` parameter is niet <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, de huidige uitzondering is opgetreden tijdens een <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blok die verantwoordelijk is voor de interne uitzondering."
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(String)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klasse met een opgegeven foutbericht."
  remarks: "Deze constructor initialiseert de <xref:System.Exception.Message>eigenschap van de nieuwe uitzondering via de `message` parameter.</xref:System.Exception.Message> De inhoud van `message` is bedoeld om te worden ge√Ønterpreteerd door mensen. De aanroeper van deze constructor is vereist om ervoor te zorgen dat deze tekenreeks gelokaliseerd voor de huidige systeemcultuur.       De volgende tabel toont de eerste waarden voor het nieuwe exemplaar.      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException>| `null`.|   | <xref:System.Exception.Message>| De fouttekenreeks bericht. |</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: public AsynchronousOperationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Het foutbericht met uitleg over de reden voor de uitzondering."
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(SerializationInfo,StreamingContext)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klasse met de geserialiseerde gegevens."
  remarks: "Deze constructor is aangeroepen tijdens de deserialisatie op het object exception verzonden via een stroom opnieuw samenstellen."
  syntax:
    content: protected AsynchronousOperationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Een <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> object dat de gegevens geserialiseerd object bevat."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Een <xref:System.Runtime.Serialization.StreamingContext>object dat de contextuele informatie over de bron- of doelserver bevat.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(String,Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initialiseert een nieuw exemplaar van de <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klasse met een opgegeven foutbericht en een verwijzing naar de interne uitzondering dat de oorzaak van deze uitzondering."
  remarks: "Een uitzondering die is gegenereerd als direct resultaat van een eerdere uitzondering moet een verwijzing bevatten naar de vorige uitzondering in de <xref:System.Exception.InnerException>eigenschap.</xref:System.Exception.InnerException> De <xref:System.Exception.InnerException>eigenschap dezelfde waarde die is doorgegeven aan de constructor.</xref:System.Exception.InnerException>       De volgende tabel toont de eerste waarden voor het nieuwe exemplaar.      | Eigenschap | Waarde |   |--------------|-----------|   | <xref:System.Exception.InnerException>| De verwijzing naar de interne uitzondering. |   | <xref:System.Exception.Message>| De fouttekenreeks bericht. |</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: public AsynchronousOperationException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Het foutbericht met uitleg over de reden voor de uitzondering."
    - id: innerException
      type: System.Exception
      description: "De <xref:System.Exception>die de oorzaak van de huidige uitzondering.</xref:System.Exception> Als de `innerException` parameter is niet <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, de huidige uitzondering is opgetreden tijdens een <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blok die verantwoordelijk is voor de interne uitzondering."
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException()
  nameWithType: AsynchronousOperationException.AsynchronousOperationException()
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException()
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(Exception)
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(String)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(SerializationInfo,StreamingContext)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(String,Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String,Exception)
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException
  nameWithType: AsynchronousOperationException.AsynchronousOperationException
